
package controller.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Apr 01 23:49:31 EEST 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "AddBook", namespace = "http://controller/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddBook", namespace = "http://controller/")

public class AddBook {

    @XmlElement(name = "arg0")
    private model.Book arg0;

    public model.Book getArg0() {
        return this.arg0;
    }

    public void setArg0(model.Book newArg0)  {
        this.arg0 = newArg0;
    }

}

