
package controller.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Apr 01 00:26:27 EEST 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "GetBooksResponse", namespace = "http://controller/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBooksResponse", namespace = "http://controller/")

public class GetBooksResponse {

    @XmlElement(name = "return")
    private java.util.List<model.Book> _return;

    public java.util.List<model.Book> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<model.Book> new_return)  {
        this._return = new_return;
    }

}

