
package controller.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sun Apr 02 14:37:59 EEST 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "UpdateBookResponse", namespace = "http://controller/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateBookResponse", namespace = "http://controller/")

public class UpdateBookResponse {


}

